apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  # Note that unlike most provider configs this one supports an array of
  # credentials. This is because each Terraform workspace uses a single
  # Crossplane provider config, but could use multiple Terraform providers each
  # with their own credentials.
  # See https://pages.github.tools.sap/cloud-orchestration/docs/advanced/MigrateExistingSetups#connect-remote-state 
  credentials:
    - filename: gcp-credentials.json
      source: Secret
      secretRef:
        namespace: default
        name: gcp-creds
        key: credentials
  # This optional configuration block can be used to inject HCL into any
  # workspace that uses this provider config, for example to setup Terraform
  # providers.
  configuration: |
    terraform {
      backend "gcs" {
        bucket = "orchestrator-tf-state-demo"
        prefix = "terraform/state"
        credentials = "gcp-credentials.json"
      }
    }